// <auto-generated />
using Student.Microservice.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using Microsoft.Extensions.DependencyInjection;
using Student.Microservice.Entities;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Internal;

namespace Student.Microservice.Migrations
{
    public static class SeedDefaultData
    {
        public static async Task SeedData(this IServiceProvider serviceProvider, ApplicationDbContext context)
        {
  
            if (context != null  )
            {
                if(!context.Students.Any())
              await SeedData(context);
            }
 
        }

        private static async Task SeedData(ApplicationDbContext context )
        {
            
                var newClass = new Class()
                {
                    Name = "1st Class"
                };
                var newClass2 = new Class()
                {
                    Name = "12nd Class"
                };
                context.Add(newClass);
                context.Add(newClass2);

                await context.SaveChangesAsync();
                var student = new Student.Microservice.Entities.Student()
                {
                    City = "Aleppo",
                    FullName = "Mohanad",
                    ClassId = 1,
                    Email = "mail@mail.com",
                    DOB = DateTime.Now,
                    DateofRegistration = DateTime.Now,
                    PhoneNumber = "1234567890",


                };
                context.Add(student);
                await context.SaveChangesAsync();
          
         
        }
    }

}
