// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using Microsoft.Extensions.DependencyInjection;
 using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Internal;
using Course.Microservice.Data;

namespace Course.Microservice.Migrations
{
    public static class SeedDefaultData
    {
        public static async Task SeedData(this IServiceProvider serviceProvider, ApplicationDbContext context)
        {
  
            if (context != null  )
            {
                if(!context.Attendances.Any())
              await SeedData(context);
            }
 
        }

        private static async Task SeedData(ApplicationDbContext context )
        {
            
                 
            
                var student = new Course.Microservice.Entities.Attendance()
                {
                 
                    FullName = "Mohanad",
                 AttendencePercentage = 99.99,
                 AttendenceDate = DateTime.Now


                };
                context.Add(student);
                await context.SaveChangesAsync();
          
         
        }
    }

}
