// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using Microsoft.Extensions.DependencyInjection;
 using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Internal;
using Course.Microservice.Data;

namespace Course.Microservice.Migrations
{
    public static class SeedDefaultData
    {
        public static async Task SeedData(this IServiceProvider serviceProvider, ApplicationDbContext context)
        {
  
            if (context != null  )
            {
                if(!context.Courses.Any())
              await SeedData(context);
            }
 
        }

        private static async Task SeedData(ApplicationDbContext context )
        {
            
                 
            
                var student = new Course.Microservice.Entities.Course()
                {
                 
                   Name = "New Course 1"


                };
            var student2 = new Course.Microservice.Entities.Course()
            {

                Name = "New Course 2"


            };
            context.Add(student);
            context.Add(student2);

            await context.SaveChangesAsync();
          
         
        }
    }

}
